const items = new vis.DataSet([
    {
        "id": 1,
        "content": "Wybrani",
        "start": "2024-11-05 1:00",
        "end": "2024-12-07 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Wybrani"
    },
    {
        "id": 2,
        "content": "Atak Tytanów T.30",
        "start": "2024-12-03 13:00",
        "end": "2024-12-07 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Atak Tytanów T.30"
    },
    {
        "id": 3,
        "content": "Gender Queer",
        "start": "2024-12-08 13:00",
        "end": "2024-12-13 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Gender Queer"
    },
    {
        "id": 4,
        "content": "Dziki robot",
        "start": "2024-12-07 1:00",
        "end": "2024-12-07 23:59",
        "group": "tv",
        "subgroup": "cinema",
        "url": null,
        "className": "cinema",
        "title": "Dziki robot"
    },
    {
        "id": 5,
        "content": "Król Lew",
        "start": "2024-12-06 1:00",
        "end": "2024-12-06 23:59",
        "group": "tv",
        "subgroup": "movie",
        "url": null,
        "className": "movie",
        "title": "Król Lew"
    },
    {
        "id": 6,
        "content": "Tulsa King s.2",
        "start": "2024-12-10 1:00",
        "end": "2024-12-19 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": "https://www.imdb.com/title/tt16358384",
        "className": "series",
        "title": "Tulsa King s.2"
    },
    {
        "id": 7,
        "content": "Atak Tytanów T.31",
        "start": "2024-12-13 13:00",
        "end": "2024-12-15 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Atak Tytanów T.31"
    },
    {
        "id": 8,
        "content": "Atak Tytanów T.32",
        "start": "2024-12-15 13:00",
        "end": "2024-12-18 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Atak Tytanów T.32"
    },
    {
        "id": 9,
        "content": "Atak Tytanów T.33",
        "start": "2024-12-18 13:00",
        "end": "2024-12-20 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Atak Tytanów T.33"
    },
    {
        "id": 10,
        "content": "Atak Tytanów T.34",
        "start": "2024-12-20 13:00",
        "end": "2024-12-21 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Atak Tytanów T.34"
    },
    {
        "id": 11,
        "content": "Money Electric: The Bitcoin Mystery",
        "start": "2024-12-08 1:00",
        "end": "2024-12-09 21:00",
        "group": "tv",
        "subgroup": "doc",
        "url": null,
        "className": "doc",
        "title": "Money Electric: The Bitcoin Mystery"
    },
    {
        "id": 12,
        "content": "John Wick",
        "start": "2024-12-20 1:00",
        "end": "2024-12-21 21:00",
        "group": "tv",
        "subgroup": "movie",
        "url": null,
        "className": "movie",
        "title": "John Wick"
    },
    {
        "id": 13,
        "content": "John Wick 2",
        "start": "2024-12-28 1:00",
        "end": "2024-12-29 21:00",
        "group": "tv",
        "subgroup": "movie",
        "url": null,
        "className": "movie",
        "title": "John Wick 2"
    },
    {
        "id": 14,
        "content": "John Wick 3",
        "start": "2024-12-30 1:00",
        "end": "2025-01-01 21:00",
        "group": "tv",
        "subgroup": "movie",
        "url": null,
        "className": "movie",
        "title": "John Wick 3"
    },
    {
        "id": 15,
        "content": "Queer Eye s.9",
        "start": "2024-12-21 1:00",
        "end": "2024-12-30 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Queer Eye s.9"
    },
    {
        "id": 16,
        "content": "Pjongjang",
        "start": "2024-12-21 13:00",
        "end": "2024-12-27 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Pjongjang"
    },
    {
        "id": 17,
        "content": "Nie zapomnij mnie",
        "start": "2024-12-27 13:00",
        "end": "2024-12-30 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Nie zapomnij mnie"
    },
    {
        "id": 18,
        "content": "Strefa Gazy: Przypisy",
        "start": "2024-12-30 13:00",
        "end": "2025-01-05 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Strefa Gazy: Przypisy"
    },
    {
        "id": 19,
        "content": "Papers, please",
        "start": "2024-12-20",
        "end": "2025-01-06",
        "group": "games",
        "subgroup": "",
        "url": null,
        "className": "",
        "title": "Papers, please"
    },
    {
        "id": 20,
        "content": "Celeste",
        "start": "2024-10-05",
        "end": "2024-12-19",
        "group": "games",
        "subgroup": "",
        "url": null,
        "className": "",
        "title": "Celeste"
    },
    {
        "id": 21,
        "content": "Włóczykij: Melodia Doliny Muminków",
        "start": "2024-12-15",
        "end": "2024-12-16",
        "group": "games",
        "subgroup": "mini",
        "url": null,
        "className": "mini",
        "title": "Włóczykij: Melodia Doliny Muminków"
    },
    {
        "id": 22,
        "content": "Siddhartha",
        "start": "2025-01-06 13:00",
        "end": "2025-01-09 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Siddhartha"
    },
    {
        "id": 23,
        "content": "Hollow Knight",
        "start": "2025-01-10",
        "end": "2025-05-31",
        "group": "games",
        "subgroup": "",
        "url": null,
        "className": "",
        "title": "Hollow Knight"
    },
    {
        "id": 24,
        "content": "Hałas",
        "start": "2025-01-09 13:00",
        "end": "2025-01-15 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Hałas"
    },
    {
        "id": 25,
        "content": "Lżejsza od swojego cienia",
        "start": "2025-01-14 13:00",
        "end": "2025-01-16 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Lżejsza od swojego cienia"
    },
    {
        "id": 26,
        "content": "Habibi",
        "start": "2025-01-17 13:00",
        "end": "2025-01-22 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Habibi"
    },
    {
        "id": 27,
        "content": "Normalni ludzie",
        "start": "2025-01-25 13:00",
        "end": "2025-01-30 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Normalni ludzie"
    },
    {
        "id": 28,
        "content": "Ghost world",
        "start": "2025-02-02 13:00",
        "end": "2025-02-03 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Ghost world"
    },
    {
        "id": 29,
        "content": "Daytripper",
        "start": "2025-02-04 13:00",
        "end": "2025-02-06 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Daytripper"
    },
    {
        "id": 30,
        "content": "Histeria Sztuki",
        "start": "2025-02-06 13:00",
        "end": "2025-02-14 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Histeria Sztuki"
    },
    {
        "id": 31,
        "content": "Nie opuszczaj mnie",
        "start": "2025-02-15 13:00",
        "end": "2025-02-23 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Nie opuszczaj mnie"
    },
    {
        "id": 32,
        "content": "Czarna ziemia",
        "start": "2025-02-25 13:00",
        "end": "2025-03-02 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book break",
        "title": "Czarna ziemia"
    },
    {
        "id": 33,
        "content": "Full Metal Alchemist t.1",
        "start": "2025-03-03 13:00",
        "end": "2025-03-05 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Full Metal Alchemist t.1"
    },
    {
        "id": 34,
        "content": "Do poprawki",
        "start": "2025-03-19 13:00",
        "end": "2025-03-20 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Do poprawki"
    },
    {
        "id": 35,
        "content": "Genialna przyjaciólka",
        "start": "2025-03-05 13:00",
        "end": "2025-03-18 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Genialna przyjaciólka"
    },
    {
        "id": 36,
        "content": "John Wick 4",
        "start": "2025-01-02 1:00",
        "end": "2025-01-04 21:00",
        "group": "tv",
        "subgroup": "movie",
        "url": null,
        "className": "movie",
        "title": "John Wick 4"
    },
    {
        "id": 37,
        "content": "Squid game s.2",
        "start": "2025-01-05 1:00",
        "end": "2025-01-11 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Squid game s.2"
    },
    {
        "id": 38,
        "content": "My happy marriage",
        "start": "2025-01-06",
        "end": "2025-01-06 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 39,
        "content": "My happy marriage",
        "start": "2025-01-13",
        "end": "2025-01-13 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 40,
        "content": "My happy marriage",
        "start": "2025-01-20",
        "end": "2025-01-20 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 41,
        "content": "My happy marriage",
        "start": "2025-01-27",
        "end": "2025-01-27 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 42,
        "content": "My happy marriage",
        "start": "2025-02-04",
        "end": "2025-02-04 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 43,
        "content": "My happy marriage",
        "start": "2025-02-10",
        "end": "2025-02-10 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 44,
        "content": "My happy marriage",
        "start": "2025-02-17",
        "end": "2025-02-17 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 45,
        "content": "My happy marriage",
        "start": "2025-02-24",
        "end": "2025-02-24 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 46,
        "content": "My happy marriage",
        "start": "2025-03-03",
        "end": "2025-03-03 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 47,
        "content": "My happy marriage",
        "start": "2025-03-10",
        "end": "2025-03-10 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 48,
        "content": "My happy marriage",
        "start": "2025-03-17",
        "end": "2025-03-17 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 49,
        "content": "My happy marriage",
        "start": "2025-03-23",
        "end": "2025-03-23 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 50,
        "content": "My happy marriage",
        "start": "2025-04-28",
        "end": "2025-04-28 23:59",
        "group": "anime",
        "subgroup": "MHM",
        "url": null,
        "className": "MHM",
        "title": "My happy marriage"
    },
    {
        "id": 51,
        "content": "Dziecko czy oszustka: Przypadek Natalii Grace",
        "start": "2025-01-09 1:00",
        "end": "2025-01-11 21:00",
        "group": "tv",
        "subgroup": "doc",
        "url": null,
        "className": "doc",
        "title": "Dziecko czy oszustka: Przypadek Natalii Grace"
    },
    {
        "id": 52,
        "content": "Penguin",
        "start": "2025-01-12 1:00",
        "end": "2025-01-19 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Penguin"
    },
    {
        "id": 53,
        "content": "Dzień Szakala",
        "start": "2025-01-20 1:00",
        "end": "2025-01-29 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Dzień Szakala"
    },
    {
        "id": 54,
        "content": "Szakal",
        "start": "2025-01-30 1:00",
        "end": "2025-01-31 21:00",
        "group": "tv",
        "subgroup": "movie",
        "url": null,
        "className": "movie",
        "title": "Szakal"
    },
    {
        "id": 55,
        "content": "Ukochane dziecko",
        "start": "2025-01-28 1:00",
        "end": "2025-01-30 21:00",
        "group": "tv",
        "subgroup": "series-alone",
        "url": null,
        "className": "series-alone",
        "title": "Ukochane dziecko"
    },
    {
        "id": 56,
        "content": "Mianujom mie Hanka",
        "start": "2025-01-30 1:00",
        "end": "2025-01-30 23:59",
        "group": "tv",
        "subgroup": "doc",
        "url": null,
        "className": "doc",
        "title": "Mianujom mie Hanka"
    },
    {
        "id": 57,
        "content": "Śleboda",
        "start": "2025-02-02 1:00",
        "end": "2025-02-09 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Śleboda"
    },
    {
        "id": 58,
        "content": "Krucjata s.2",
        "start": "2025-02-11 1:00",
        "end": "2025-02-23 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Krucjata s.2"
    },
    {
        "id": 59,
        "content": "Neon Genesis Evangelion",
        "start": "2025-02-11",
        "end": "2025-02-28",
        "group": "anime",
        "subgroup": "",
        "url": null,
        "className": "",
        "title": "Neon Genesis Evangelion"
    },
    {
        "id": 60,
        "content": "End of Evangelion",
        "start": "2025-03-12",
        "end": "2025-03-12 23:59",
        "group": "anime",
        "subgroup": "",
        "url": null,
        "className": "",
        "title": "End of Evangelion"
    },
    {
        "id": 61,
        "content": "Ocet jabłkowy",
        "start": "2025-02-24 1:00",
        "end": "2025-02-27 21:00",
        "group": "tv",
        "subgroup": "series-alone",
        "url": null,
        "className": "series-alone",
        "title": "Ocet jabłkowy"
    },
    {
        "id": 62,
        "content": "Kibic",
        "start": "2025-02-25 1:00",
        "end": "2025-03-01 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Kibic"
    },
    {
        "id": 63,
        "content": "Zbrodnie po sąsiedzku",
        "start": "2025-03-02 1:00",
        "end": "2025-03-13 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Zbrodnie po sąsiedzku"
    },
    {
        "id": 64,
        "content": "Ponyo",
        "start": "2025-03-14",
        "end": "2025-03-15",
        "group": "anime",
        "subgroup": "",
        "url": null,
        "className": " dnf",
        "title": "Ponyo"
    },
    {
        "id": 65,
        "content": "Daredevil",
        "start": "2025-03-15 1:00",
        "end": "2025-03-15 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series dnf",
        "title": "Daredevil"
    },
    {
        "id": 66,
        "content": "W pułapce myśli",
        "start": "2025-02-22 13:00",
        "end": "2025-02-23 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book dnf",
        "title": "W pułapce myśli"
    },
    {
        "id": 67,
        "content": "Dear Zachary",
        "start": "2025-07-25 1:00",
        "end": "2025-07-25 23:59",
        "group": "tv",
        "subgroup": "doc",
        "url": null,
        "className": "doc",
        "title": "Dear Zachary"
    },
    {
        "id": 68,
        "content": "Sound of sch",
        "start": "2025-02-24 13:00",
        "end": "2025-02-24 23:59",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Sound of sch"
    },
    {
        "id": 69,
        "content": "Marka osobista w branży IT",
        "start": "2025-03-21 13:00",
        "end": "2025-03-22 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Marka osobista w branży IT"
    },
    {
        "id": 70,
        "content": "Potwory",
        "start": "2025-03-23 13:00",
        "end": "2025-03-30 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Potwory"
    },
    {
        "id": 71,
        "content": "Lockerbie",
        "start": "2025-03-31 1:00",
        "end": "2025-04-05 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Lockerbie"
    },
    {
        "id": 72,
        "content": "Reacher",
        "start": "2025-04-06 1:00",
        "end": "2025-04-16 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Reacher"
    },
    {
        "id": 73,
        "content": "Black Mirror",
        "start": "2025-04-17 1:00",
        "end": "2025-04-24 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Black Mirror"
    },
    {
        "id": 74,
        "content": "Slow horses",
        "start": "2025-04-27 1:00",
        "end": "2025-05-02 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Slow horses"
    },
    {
        "id": 75,
        "content": "Severance",
        "start": "2025-04-27 1:00",
        "end": "2025-05-06 21:00",
        "group": "tv",
        "subgroup": "series-alone",
        "url": null,
        "className": "series-alone",
        "title": "Severance"
    },
    {
        "id": 76,
        "content": "Demon w rodzinie: Sprawa Ruby Franke",
        "start": "2025-05-05 1:00",
        "end": "2025-05-07 21:00",
        "group": "tv",
        "subgroup": "doc",
        "url": null,
        "className": "doc",
        "title": "Demon w rodzinie: Sprawa Ruby Franke"
    },
    {
        "id": 77,
        "content": "Ścieżka",
        "start": "2025-03-30 13:00",
        "end": "2025-04-02 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Ścieżka"
    },
    {
        "id": 78,
        "content": "Dojrzewanie",
        "start": "2025-03-16 1:00",
        "end": "2025-03-19 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Dojrzewanie"
    },
    {
        "id": 79,
        "content": "Dexter: Original sin",
        "start": "2025-03-20 1:00",
        "end": "2025-03-30 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Dexter: Original sin"
    },
    {
        "id": 80,
        "content": "Śmieci",
        "start": "2025-04-03 13:00",
        "end": "2025-04-07 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "Śmieci"
    },
    {
        "id": 81,
        "content": "Ocean na końcu drogi",
        "start": "2025-04-08 13:00",
        "end": "2025-04-11 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Ocean na końcu drogi"
    },
    {
        "id": 82,
        "content": "Historia nowego nazwiska",
        "start": "2025-04-12 13:00",
        "end": "2025-04-21 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Historia nowego nazwiska"
    },
    {
        "id": 83,
        "content": "Powolna produktywność",
        "start": "2025-04-22 13:00",
        "end": "2025-04-27 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book break",
        "title": "Powolna produktywność"
    },
    {
        "id": 84,
        "content": "Historia ucieczki",
        "start": "2025-04-28 13:00",
        "end": "2025-05-11 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book",
        "title": "Historia ucieczki"
    },
    {
        "id": 85,
        "content": "Bosch: Legacy",
        "start": "2025-05-03 1:00",
        "end": "2025-05-13 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Bosch: Legacy"
    },
    {
        "id": 86,
        "content": "Silos",
        "start": "2025-05-14 1:00",
        "end": "2025-05-26 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Silos"
    },
    {
        "id": 87,
        "content": "Mythic Quest",
        "start": "2025-05-27 1:00",
        "end": "2025-06-04 21:00",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Mythic Quest"
    },
    {
        "id": 88,
        "content": "PTSD",
        "start": "2025-05-12 13:00",
        "end": "2025-05-13 12:00",
        "group": "books",
        "subgroup": "comics",
        "url": null,
        "className": "comics",
        "title": "PTSD"
    },
    {
        "id": 89,
        "content": "Powolna produktywność",
        "start": "2025-05-14 13:00",
        "end": "2025-05-16 12:00",
        "group": "books",
        "subgroup": "book",
        "url": null,
        "className": "book return",
        "title": "Powolna produktywność"
    },
    {
        "id": 90,
        "content": "Jerry Springer: Kłótnie, kamera, akcja",
        "start": "2025-02-22 1:00",
        "end": "2025-02-22 23:59",
        "group": "tv",
        "subgroup": "series",
        "url": null,
        "className": "series",
        "title": "Jerry Springer: Kłótnie, kamera, akcja"
    },
    {
        "id": 91,
        "content": "Sprzątaczka",
        "start": "2025-05-15 1:00",
        "end": "2025-05-15 23:59",
        "group": "tv",
        "subgroup": "series-alone",
        "url": null,
        "className": "series-alone break",
        "title": "Sprzątaczka"
    },
    {
        "id": 92,
        "content": "Sprzątaczka",
        "start": "2025-06-13 1:00",
        "end": "2025-06-13 23:59",
        "group": "tv",
        "subgroup": "series-alone",
        "url": null,
        "className": "series-alone break return",
        "title": "Sprzątaczka"
    }
]);